### ISSUE TITLE
unable to create international shipment label

### ISSUE THREAD

**Issue by nikhilkevo** [vphat28/purolator-magento2#4]
it show shipment error

**Comment by vphat28** [comment]
pls provide steps

**Comment by nikhilkevo** [comment]
Firstly I placed the order with an international address after creating the invoice 
I have created, the shipment label but it throw the exception of a shipment error.

I have used these address 
Guentzelstrasse
11
Neu-bamberg, Rheinland-Pfalz, 55546
Germany
T: 0987653321

If I used a local address then it will work
